name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install latest rust toolchain
          uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              default: true
              override: true

        - name: Release lib
          uses: katyo/publish-crates@v1
          with:
              path: './pwnd'
              registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

#        - name: Release CLI
#          uses: katyo/publish-crates@v1
#          with:
#              path: './pwnd_cli'
#              registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
#              dry-run: true