name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2#

        - name: Install latest rust toolchain
          uses: actions-rs/toolchain@v1
          with:
              toolchain: stable
              default: true
              override: true

        - name: Release PWN lib
          uses: katyo/publish-crates@v1
          with:
              path: './pwn'
              args: --no-verify
              dry-run: true

        - name: Release PWN CLI
          uses: katyo/publish-crates@v1
          with:
              path: './pwn_cli'
              args: --no-verify
              dry-run: true