name: Rust

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
        
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
        

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-darwin
        default: true
        override: true
        

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
